[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NERStreamlitApp"
version = "0.1.0"
description = "Custom Named Entity Recognition using spaCy and Streamlit"
requires-python = ">=3.8,<3.12"

[tool.setuptools]
packages = [] 