[theme]
primaryColor = "#FF4B4B" 
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = true
enableWebsocketCompression = true
maxUploadSize = 10
runOnSave = false

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
showErrorDetails = true

[runner]
fastReruns = true 