[theme]
primaryColor = "#FF4B4B" 
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 50
runOnSave = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false
logLevel = "info" 