# This file is used by Streamlit Cloud to store secrets
# You can add any environment-specific configurations here

[general]
# No specific secrets needed for this application

[server]
# Server configuration
maxUploadSize = 10
enableCORS = false 